version: "3"

networks:
  app_net:

services:
  phpfpm:
    container_name: phpfpm
    build: ./php

    # image: php:7.4-fpm
    volumes:
      - "./www:/www"
      - "./php.ini:/usr/local/etc/php/conf.d/php.ini"
    networks:
      - "app_net"
  nginx:
    container_name: nginx
    image: nginx:1.19.8
    volumes:
      - "./www:/www"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "8080:80"
    networks:
      - "app_net"
  mysql:
    container_name: "mysql"
    image: mysql:5.7
    networks:
      - "app_net"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=db"
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    networks:
      - "app_net"
    ports:
      - "8081:80"
    environment:
      - "PMA_HOST=mysql"
      - "PMA_USER=root"
      - "PMA_PASSWORD=root"
      - "PMA_PMADB=db"
      - "PMA_PORT=3306"
